// <auto-generated />
namespace Sds.FileStorage.EntityFramework
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class File_Field_Deleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(File_Field_Deleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201612251404334_File_Field_Deleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
