// <auto-generated />
namespace Sds.FileStorage.EntityFramework
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFileId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFileId));
        
        string IMigrationMetadata.Id
        {
            get { return "201701262213310_Add FileId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
